### ISSUE TITLE
Sage Attention 2 not work with Pytorch Compile

### ISSUE THREAD

**Issue by pivtienduc** [thu-ml/SageAttention#162]
Hi @jt-zhang 

It seem that with the pytorch compile have not worked with the sage attention

I try to use just Flux basic ksampler workflow but get an full of noise image like this, the inference speed still increase but image is broken

![Image](https://github.com/user-attachments/assets/2349f53d-be39-4ae2-9e62-f348a66010cb)

This is my comfyUI:

![Image](https://github.com/user-attachments/assets/aa3e0b46-7a53-4460-b66b-897157c90e77)

When I turn off Sage Attention either pytorch cross attention or xformers, everything work fine:

![Image](https://github.com/user-attachments/assets/5e701b55-dd2c-4090-84da-171d73b12e0a)

I already test many time with many ComfyUI version and pytorch version, reinstall ComfyUI many times the problem still persist

Anything involve with Sage Attention and Torch Compile will create a noise image

However someone who own RTX4000s series will not encouter this problem. My gpu is 3090, is it a hardware related ?

Please support us, thank you so much

**Comment by pivtienduc** [comment]
> What if you use SageAttention but don't use torch.compile?

Then everything work fine, 

And I found out that first time when I get a noise image. Disable sage attention then run with pytorch attention and let ComfyUI run pytorch compile then turn sage attention on, no more noise image but also there aren't any speed up with Torch Compile anymore, it run like no compile at all.

**Comment by StrongerXi** [comment]
This is strange, I've seen a few reports of sage attention not working with torch compile, I'll try look into this in the next week or so. You also mentioned Sage Attention 2 in your title, have you tried older version of sage attention?

**Comment by pivtienduc** [comment]
> This is strange, I've seen a few reports of sage attention not working with torch compile, I'll try look into this in the next week or so. You also mentioned Sage Attention 2 in your title, have you tried older version of sage attention?

I haven't try sage attention 1 yet, ok let me check later then give you the result

**Comment by pivtienduc** [comment]
> This is strange, I've seen a few reports of sage attention not working with torch compile, I'll try look into this in the next week or so. You also mentioned Sage Attention 2 in your title, have you tried older version of sage attention?

Well result is still the same. This is done on freshly install ComfyUI I just installed few hours ago

![Image](https://github.com/user-attachments/assets/0eae90e2-6f3c-4df3-ba9d-08cc2e6dbf50)

![Image](https://github.com/user-attachments/assets/65a02885-bb47-4990-a369-cb306bf78daf)

Please check

**Comment by BaseMe2** [comment]
Same problem here. 

Win11 24H2 build 26100.3194, 
RTX5070ti driver576.28, 
pytorch 2.7.0+cu128, 
Cuda12.8, 
Python 3.12.9, 
sageattention-2.1.1+cu128torch2.8.0-cp312-cp312-win_amd64
triton-3.2.0-cp312-cp312-win_amd64 
Comfyui 0.3.33

**Comment by BaseMe2** [comment]
related: https://github.com/woct0rdho/triton-windows/issues/120

**Comment by pikerbright** [comment]
@pivtienduc @StrongerXi I found that query, key, value input stride cause that sage attention can't work with torch compile.
following code can work.
```
def sageattention_forward(
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attn_mask: Optional[torch.Tensor] = None,
    dropout_p: float = 0.0,
    is_causal: bool = False,
    *,
    scale: Optional[float] = None,
) -> torch.Tensor:
    query = query.permute(0, 2, 1, 3)
    key = key.permute(0, 2, 1, 3)
    value = value.permute(0, 2, 1, 3)
    out = sageattn(
        query,
        key,
        value,
        attn_mask=attn_mask,
        dropout_p=dropout_p,
        is_causal=is_causal,
        scale=scale,
        tensor_layout='NHD'
    )
    return out.permute(0, 2, 1, 3)
```

**Comment by pivtienduc** [comment]
> [@pivtienduc](https://github.com/pivtienduc) [@StrongerXi](https://github.com/StrongerXi) I found that query, key, value input stride cause that sage attention can't work with torch compile. following code can work.
> 
> ```
> def sageattention_forward(
>     query: torch.Tensor,
>     key: torch.Tensor,
>     value: torch.Tensor,
>     attn_mask: Optional[torch.Tensor] = None,
>     dropout_p: float = 0.0,
>     is_causal: bool = False,
>     *,
>     scale: Optional[float] = None,
> ) -> torch.Tensor:
>     query = query.permute(0, 2, 1, 3)
>     key = key.permute(0, 2, 1, 3)
>     value = value.permute(0, 2, 1, 3)
>     out = sageattn(
>         query,
>         key,
>         value,
>         attn_mask=attn_mask,
>         dropout_p=dropout_p,
>         is_causal=is_causal,
>         scale=scale,
>         tensor_layout='NHD'
>     )
>     return out.permute(0, 2, 1, 3)
> ```

Hi @StrongerXi 

Can you take a look about it ?

Thank you so much

**Comment by woct0rdho** [comment]
Hi all, here is one more thing to consider: Did you launch ComfyUI with `--fast`?

@pivtienduc Looking from your log, there is `Enabled fp16 accumulation`.

I've found cases where `--fast fp16_accumulation` (or simply `--fast` which enables all fast options) causes the output to be noise, while `--fast cublas_ops` seems to be fine. (`--fast fp8_matrix_mult` doesn't work on RTX 30xx so I haven't tested it yet)

It's the same as OP described: When running the ComfyUI official Flux workflow (with GGUF model, but the problem is unlikely in GGUF) using SageAttention (launch with `--use-sage-attention`) and a compile node, the output is noise. When using only SageAttention, or only the compile node (with xformers attention), the output is fine.

I did not see significant speedup with `--fast fp16_accumulation`, so it's better to disable it in exchange for SageAttention + compile. BTW, `--fast cublas_ops` has some speedup for SDXL so I enable it.

I'm using torch 2.7.1+cu128, sageattention 2.1.1, triton-windows 3.3.1, cublas_ops 0.0.5, xformers 0.0.30, ComfyUI bd951a7

Looking from the reports here, this happens on RTX 30xx, 40xx, and 50xx.

**Comment by pivtienduc** [comment]
> Hi all, here is one more thing to consider: Did you launch ComfyUI with `--fast`?
> 
> [@pivtienduc](https://github.com/pivtienduc) Looking from your log, there is `Enabled fp16 accumulation`.
> 
> I've found cases where `--fast fp16_accumulation` (or simply `--fast` which enables all fast options) causes the output to be noise, while `--fast cublas_ops` seems to be fine. (`--fast fp8_matrix_mult` doesn't work on RTX 30xx so I haven't tested it yet)
> 
> It's the same as OP described: When running the ComfyUI official Flux workflow (with GGUF model, but the problem is unlikely in GGUF) using SageAttention (launch with `--use-sage-attention`) and a compile node, the output is noise. When using only SageAttention, or only the compile node (with xformers attention), the output is fine.
> 
> I did not see significant speedup with `--fast fp16_accumulation`, so it's better to disable it in exchange for SageAttention + compile. BTW, `--fast cublas_ops` has some speedup for SDXL so I enable it.
> 
> I'm using torch 2.7.1+cu128, sageattention 2.1.1, triton-windows 3.3.1, cublas_ops 0.0.5, xformers 0.0.30, ComfyUI bd951a7, RTX 3080.

Thank you so much. I will try --fast cublas_ops

**Comment by woct0rdho** [comment]
@jt-zhang Maybe in SageAttention we can add a warning if `torch.backends.cuda.matmul.allow_fp16_accumulation` is enabled

**Comment by pivtienduc** [comment]
> Hi all, here is one more thing to consider: Did you launch ComfyUI with `--fast`?
> 
> [@pivtienduc](https://github.com/pivtienduc) Looking from your log, there is `Enabled fp16 accumulation`.
> 
> I've found cases where `--fast fp16_accumulation` (or simply `--fast` which enables all fast options) causes the output to be noise, while `--fast cublas_ops` seems to be fine. (`--fast fp8_matrix_mult` doesn't work on RTX 30xx so I haven't tested it yet)
> 
> It's the same as OP described: When running the ComfyUI official Flux workflow (with GGUF model, but the problem is unlikely in GGUF) using SageAttention (launch with `--use-sage-attention`) and a compile node, the output is noise. When using only SageAttention, or only the compile node (with xformers attention), the output is fine.
> 
> I did not see significant speedup with `--fast fp16_accumulation`, so it's better to disable it in exchange for SageAttention + compile. BTW, `--fast cublas_ops` has some speedup for SDXL so I enable it.
> 
> I'm using torch 2.7.1+cu128, sageattention 2.1.1, triton-windows 3.3.1, cublas_ops 0.0.5, xformers 0.0.30, ComfyUI bd951a7
> 
> Looking from the reports here, this happens on RTX 30xx, 40xx, and 50xx.

Hi @woct0rdho 

The thing that when I use --fast fp16_accumulation image generation is faster.

With --fast fp16_accumulation my generation speed higher than without --fast but with Torch Compile.

Average time for 3090 generation --fast fp16_accumulation 16 step 1920x1080 is about 32 seconds
While average for 3090 generation without --fast but with compile 16 step 1920x1080 (not counting compile time) is about 38 seconds

Quality is not degrade by any mean and of course images are changed but still look good for me.

So I chose to go with --fast fp16_accumulation without using Torch Compile at the end.  And with --fast, compile still work with Wan2.1.

**Comment by jason-huang03** [comment]
Hi, I cannot reproduce the problem on RTX4090 when using command line to generate videos with huggingface diffusers (I am not familiar with comfyui). However, after comparing with the code of flashattention, I find that sageattention does not correctly specify the cuda stream. [This branch](https://github.com/thu-ml/SageAttention/tree/parallel_compile) contains the fixed code. Could you please try again?

**Comment by jason-huang03** [comment]
Could anyone provide a python script that can reproduce the blurring problem (also please provide the torch and cuda version)?

**Comment by woct0rdho** [comment]
I don't know if I can find a minimal reproducer but I'll try it

**Comment by pivtienduc** [comment]
> Hi, I cannot reproduce the problem on RTX4090 when using command line to generate videos with huggingface diffusers (I am not familiar with comfyui). However, after comparing with the code of flashattention, I find that sageattention does not correctly specify the cuda stream. [This branch](https://github.com/thu-ml/SageAttention/tree/parallel_compile) contains the fixed code. Could you please try again?

Still the same. I just compile and install a new wheel with your fixed code but result is the same:

<img width="1789" height="1632" alt="Image" src="https://github.com/user-attachments/assets/df699ac2-9a5b-4ea4-8349-d2e2bcf55241" />

<img width="1537" height="1574" alt="Image" src="https://github.com/user-attachments/assets/8201fd65-6073-44ea-a2cf-eed49127b4aa" />

However I found something interesting:

I used KsamplerNAG to enable negative prompt with Flux I found out that in the process of generate image by enable live preview , from 0% - 60% the image process fine with all the speed buffs, however from 61% to 100% noise is produce:

This is the image of about 60% process: 

<img width="2485" height="1586" alt="Image" src="https://github.com/user-attachments/assets/2d0bea21-e33e-4df3-8e15-3295c7a143fe" />

This is image of 100% process:

<img width="2260" height="1504" alt="Image" src="https://github.com/user-attachments/assets/7a8223d3-4d1f-4e8f-9a97-d0b4895b9b5f" />

Unfortunately NAG node does not have KsamplerAdvance to test which step noise is applied which step is fined.

And also NAG node make the image appear than just pure noise like normal Ksampler node

PS: normal Ksampler make 100% of the time is pure noise when I use live preview

**Comment by jason-huang03** [comment]
@pivtienduc you mean that under some configurations sageattention will produce the correct result when using torch.compile? what gpu do you use?

**Comment by pivtienduc** [comment]
> [@pivtienduc](https://github.com/pivtienduc) you mean that under some configurations sageattention will produce the correct result when using torch.compile? what gpu do you use?

I used 3090 and yes maybe in some configurations sageattention will work well with compile

**Comment by jason-huang03** [comment]
> > [@pivtienduc](https://github.com/pivtienduc) you mean that under some configurations sageattention will produce the correct result when using torch.compile? what gpu do you use?
> 
> I used 3090 and yes maybe in some configurations sageattention will work well with compile

I shall rent a 3090 to check the result.

**Comment by jason-huang03** [comment]
@pivtienduc I test on RTX3090 using script in example/,  and cannot reproduce the problem. I use torch 2.5.1 with cuda 12.4. What torch and cuda version do you use?

**Comment by pivtienduc** [comment]
> [@pivtienduc](https://github.com/pivtienduc) I test on RTX3090 using script in example/, and cannot reproduce the problem. I use torch 2.5.1 with cuda 12.4. What torch and cuda version do you use?

Here is my comfyUI system:

![Image](https://github.com/user-attachments/assets/2f07d825-6ad7-4598-bcd4-3b7bc80f6c29)

**Comment by guilhermeleobas** [comment]
Hi folks, I just pushed a PR (https://github.com/thu-ml/SageAttention/pull/218) that adds torch.compile support for SageAttention. If anyone could try it out and report any bugs. I'd be happy to fix them.

**Comment by pivtienduc** [comment]
> Hi folks, I just pushed a PR ([#218](https://github.com/thu-ml/SageAttention/pull/218)) that adds torch.compile support for SageAttention. If anyone could try it out and report any bugs. I'd be happy to fix them.

I already test so far not good. Bug is still the same 50% step is good then another last 50% step ksampler add only noise:

<img width="3840" height="850" alt="Image" src="https://github.com/user-attachments/assets/f91ad789-a1cd-457b-b491-65bca9838169" />

I test with both NAG Ksampler and normal Ksampler:

<img width="2442" height="783" alt="Image" src="https://github.com/user-attachments/assets/8196e0d5-0818-4b9a-adeb-3976b00adb35" />

<img width="2320" height="1386" alt="Image" src="https://github.com/user-attachments/assets/ab3039c0-c0c5-4eb7-a474-2365e44418c4" />

<img width="2049" height="1031" alt="Image" src="https://github.com/user-attachments/assets/8edf4264-d436-4ad2-957d-144da0a8514c" />


50% steps, image still good:

<img width="2504" height="1414" alt="Image" src="https://github.com/user-attachments/assets/0047362f-80c5-4db2-9722-57f1de4acde2" />

100% steps, all is noises

<img width="2310" height="1348" alt="Image" src="https://github.com/user-attachments/assets/7d15b847-f417-4cc9-8e45-e0ff5ea8fcce" />

Thank for your effort anyway.

**Comment by guilhermeleobas** [comment]
Hi @pivtienduc, thanks for trying it out. Without `torch.compile`, do you see any noise? What is the expected output? Do you have a python script that I can run to find where torch.compile is getting it wrong?

**Comment by pivtienduc** [comment]
> Hi [@pivtienduc](https://github.com/pivtienduc), thanks for trying it out. Without `torch.compile`, do you see any noise? What is the expected output? Do you have a python script that I can run to find where torch.compile is getting it wrong?

When I disable torch compile, everything run normal, nothing unusual. Output is crystal clear as it should be. I use ComfyUI so I don't know how to make a script, sorry.

**Comment by guilhermeleobas** [comment]
Can you run ComfyUI with `TORCH_LOGS=+graph_breaks`?

**Comment by pivtienduc** [comment]
> Can you run ComfyUI with `TORCH_LOGS=+graph_breaks`?

You mean put in the *.bat file when I start comfyUI right ?
At the moment my settings when start comfyui is:
.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --use-sage-attention --fast --disable-smart-memory --reserve-vram 4.0
pause

So where do I put your command ?

**Comment by woct0rdho** [comment]
@pivtienduc In Windows bat, it should be like
```bat
set TORCH_LOGS=+graph_breaks
.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --use-sage-attention --fast --disable-smart-memory --reserve-vram 4.0
```

Although I guess the problem is some arithmetic precision rather than graph break

**Comment by pivtienduc** [comment]
> [@pivtienduc](https://github.com/pivtienduc) In Windows bat, it should be like
> 
> set TORCH_LOGS=+graph_breaks
> .\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --use-sage-attention --fast --disable-smart-memory --reserve-vram 4.0
> Although I guess the problem is some arithmetic precision rather than graph break

When I run with TORCH_LOGS=+graph_breaks torch compile can run normally, image output is fine but the speed is worst 200% slower than without TORCH_LOGS=+graph_breaks. It seem disable sageattention and teacache.

**Comment by woct0rdho** [comment]
Hmmm then it seems to be an issue of PyTorch. Conceptually, enabling some logging should definitely not change the result

I heard there are some improvements about graph break in PyTorch 2.8 but I haven't checked

**Comment by guilhermeleobas** [comment]
> When I run with TORCH_LOGS=+graph_breaks torch compile can run normally, image output is fine but the speed is worst 200% slower than without TORCH_LOGS=+graph_breaks. It seem disable sageattention and teacache.

Can you paste the logs here?

**Comment by pivtienduc** [comment]
> > When I run with TORCH_LOGS=+graph_breaks torch compile can run normally, image output is fine but the speed is worst 200% slower than without TORCH_LOGS=+graph_breaks. It seem disable sageattention and teacache.
> 
> Can you paste the logs here?

Sorry for the late reply, so many models to try this week:

Here is the broken workflow when I run with TORCH_LOGS=+graph_breaks 

<img width="3685" height="1689" alt="Image" src="https://github.com/user-attachments/assets/89cbba8a-3f80-48ef-9643-886b382f5398" />

Here is the log file I run together with this broken workflow:

[comfyui.log](https://github.com/user-attachments/files/21610474/comfyui.log)

And this is the image when I just turn off the compile node:

<img width="3670" height="1678" alt="Image" src="https://github.com/user-attachments/assets/4c730987-70c8-4b88-9d85-5c8407dfc27d" />

And this is the log of turn off compile node (right after broken compile node run)

[comfyui-turnoff compile.log](https://github.com/user-attachments/files/21610512/comfyui-turnoff.compile.log)

**Comment by pivtienduc** [comment]
> Hmmm then it seems to be an issue of PyTorch. Conceptually, enabling some logging should definitely not change the result
> 
> I heard there are some improvements about graph break in PyTorch 2.8 but I haven't checked

Sorry for the mistake the last time I run TORCH_LOGS=+graph_breaks I also use --fast cublas_ops that why ComfyUI not speed up

**Comment by guilhermeleobas** [comment]
Thanks for the logs @pivtienduc. I can see one relevant graph break on `torch.cuda.set_device(...)`, which should be expected. I'll try to reproduce your workflow on ComfyUI.

**Comment by StrongerXi** [comment]
So I tested with 3090 on a Linux machine, sage attention 1.0.6 and almost the exact same configuration as the original issue (except for python 3.12.11 v.s. 3.12.9, which I don't think should affect things this much), but no noise at all:
```
Total VRAM 24135 MB, total RAM 96492 MB
pytorch version: 2.7.0+cu128
Enabled fp16 accumulation.
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using sage attention
Python version: 3.12.11 | packaged by conda-forge | (main, Jun  4 2025, 14:45:31) [GCC 13.3.0]
ComfyUI version: 0.3.30
ComfyUI frontend version: 1.17.11
```

This makes me think it's a windows-specific issue. Moreover, since `fp16_accumulation` only affects the matmul kernels in pytorch (trades precision for perf), my guess is that the combination of these methods made precision really bad, and resulted in noisy output, because each method trades a bit of precision for performance:
1. sage attention
2. fp16_accumulation
3. torch.compile

@woct0rdho @pivtienduc would one of you please try running a noisy workflow (with all the methods above) with this flag on? `TORCHINDUCTOR_EMULATE_PRECISION_CASTS=1`. So basically
```
set TORCHINDUCTOR_EMULATE_PRECISION_CASTS=1
.\python_embeded\python.exe -s ComfyUI\main.py ......all the args you had......
```

**Comment by StrongerXi** [comment]
Also @pivtienduc could you share the NAG workflow json? The graph breaks look a bit odd, I can try taking a look.

**Comment by woct0rdho** [comment]
I just checked that this issue does not happen with SageAttention 1, and happens with SageAttention 2, see https://github.com/comfyanonymous/ComfyUI/issues/8689#issuecomment-3177394408

**Comment by pivtienduc** [comment]
> Also [@pivtienduc](https://github.com/pivtienduc) could you share the NAG workflow json? The graph breaks look a bit odd, I can try taking a look.

Sure. Here you are.

[Flux Simple.json](https://github.com/user-attachments/files/21726107/Flux.Simple.json)

**Comment by pivtienduc** [comment]
> So I tested with 3090 on a Linux machine, sage attention 1.0.6 and almost the exact same configuration as the original issue (except for python 3.12.11 v.s. 3.12.9, which I don't think should affect things this much), but no noise at all:
> 
> ```
> Total VRAM 24135 MB, total RAM 96492 MB
> pytorch version: 2.7.0+cu128
> Enabled fp16 accumulation.
> Set vram state to: NORMAL_VRAM
> Disabling smart memory management
> Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
> Using sage attention
> Python version: 3.12.11 | packaged by conda-forge | (main, Jun  4 2025, 14:45:31) [GCC 13.3.0]
> ComfyUI version: 0.3.30
> ComfyUI frontend version: 1.17.11
> ```
> 
> This makes me think it's a windows-specific issue. Moreover, since `fp16_accumulation` only affects the matmul kernels in pytorch (trades precision for perf), my guess is that the combination of these methods made precision really bad, and resulted in noisy output, because each method trades a bit of precision for performance:
> 
> 1. sage attention
> 2. fp16_accumulation
> 3. torch.compile
> 
> [@woct0rdho](https://github.com/woct0rdho) [@pivtienduc](https://github.com/pivtienduc) would one of you please try running a noisy workflow (with all the methods above) with this flag on? `TORCHINDUCTOR_EMULATE_PRECISION_CASTS=1`. So basically
> 
> ```
> set TORCHINDUCTOR_EMULATE_PRECISION_CASTS=1
> .\python_embeded\python.exe -s ComfyUI\main.py ......all the args you had......
> ```

Hi I just install pytorch 2.8 and confirm that set TORCHINDUCTOR_EMULATE_PRECISION_CASTS=1 make it work to some degrees. It will be hit or miss since I get this error:

<img width="3694" height="1691" alt="Image" src="https://github.com/user-attachments/assets/2ea66e36-cb45-4fd3-aa92-ae272cedb841" />

After restart ComfyUI sometime I don't get this error, sometimes I get. 

Here is my ComfyUI log show something about my error:

[comfyui.log](https://github.com/user-attachments/files/21726715/comfyui.log)

This is the first time I see this error beside of noise image when compile.

**Comment by pivtienduc** [comment]
It very weird that since I upgrade to Pytorch 2.8 I get a lot of "Python int too large to convert to C long" error when I compile, no matter what I do enable or disable Sage Attention or Fast fp16 accumulation. It seem like ComfyUI has not support full for pytorch 2.8

**Comment by woct0rdho** [comment]
@pivtienduc What are your Triton and SageAttention versions now, including the detailed minor versions? PyTorch 2.8 should work with triton-windows 3.4.0.post20 .

In very old triton-windows (before 3.1.0.post9) there was a bug about C long, see https://github.com/triton-lang/triton/pull/5351

If you're using the correct Triton version but still see the error about C long, then I guess it's likely a Windows-specific bug. Windows is notorious that even on 64-bit OS, C long has only 32 bits rather than 64 bits. But I guess this is not directly related to the noise output.

**Comment by pivtienduc** [comment]
> [@pivtienduc](https://github.com/pivtienduc) What are your Triton and SageAttention versions now, including the detailed minor versions? PyTorch 2.8 should work with triton-windows 3.4.0.post20 .
> 
> In very old triton-windows (before 3.1.0.post9) there was a bug about C long, see [triton-lang/triton#5351](https://github.com/triton-lang/triton/pull/5351)
> 
> If you're using the correct Triton version but still see the error about C long, then I guess it's likely a Windows-specific bug. Windows is notorious that even on 64-bit OS, C long has only 32 bits rather than 64 bits. But I guess this is not directly related to the noise output.

I use the corrected Triton and sometimes I can compile, sometimes I don't. So I don't know what is the cause. I just update Windows, reinstal GPU driver with DDU, reinstall ComfyUI, problem still the same. Can you check my log above to see what happens, there are some code tell something about this error in the log (at the end of the log)

**Comment by woct0rdho** [comment]
I've seen your log but I can't quickly find the cause. When I have time I'll try to install your custom nodes and reproduce it

**Comment by buzzjeux** [comment]
@StrongerXi Just for your information

```
set TORCHINDUCTOR_EMULATE_PRECISION_CASTS=1
.\python_embeded\python.exe -s ComfyUI\main.py ......all the args you had......
```

That working for me, no noise output anymore, does it bypass the fp16 accumulation or just solve the problem without any other negative effects??

> Total VRAM 16379 MB, total RAM 65463 MB
> pytorch version: 2.8.0+cu128
> Enabled fp16 accumulation.
> Set vram state to: NORMAL_VRAM
> Disabling smart memory management
> Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
> Using sage attention
> Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
> ComfyUI version: 0.3.50
> ComfyUI frontend version: 1.24.4

**Comment by StrongerXi** [comment]
> That working for me, no noise output anymore

@buzzjeux great to hear! Please help spread the message to help others who run into this issue:).

> does it bypass the fp16 accumulation or just solve the problem without any other negative effects??

It's a bit complicated, but `TORCHINDUCTOR_EMULATE_PRECISION_CASTS=1` won't affect `--fast fp16_accumulation` (which applies to the default CUBLAS matmul kernels PyTorch uses). Rather, it tells `torch.compile` to preserve the downcasts to fp16 in the middle of some fp32 computations ([example](https://github.com/pytorch/pytorch/pull/131595#issuecomment-2251171715)). So yeah, this flag actually _reduces_ the mathematical precision and might make things _a tad_ slower (if at all, I haven't noticed any slow down).

You can think of it as, by default `torch.compile` makes fp16 compute faster and _more_ precise, but turns out the models and various optimization methods (which were trained/tuned without compile), might "prefer" the _less_ precise numerics (in the mathematical sense), and that's when you need `TORCHINDUCTOR_EMULATE_PRECISION_CASTS=1`.

I'll chat with the team and see if we can make this experience better for users.

**Comment by pivtienduc** [comment]
> > That working for me, no noise output anymore
> 
> [@buzzjeux](https://github.com/buzzjeux) great to hear! Please help spread the message to help others who run into this issue:).
> 
> > does it bypass the fp16 accumulation or just solve the problem without any other negative effects??
> 
> It's a bit complicated, but `TORCHINDUCTOR_EMULATE_PRECISION_CASTS=1` won't affect `--fast fp16_accumulation` (which applies to the default CUBLAS matmul kernels PyTorch uses). Rather, it tells `torch.compile` to preserve the downcasts to fp16 in the middle of some fp32 computations ([example](https://github.com/pytorch/pytorch/pull/131595#issuecomment-2251171715)). So yeah, this flag actually _reduces_ the mathematical precision and might make things _a tad_ slower (if at all, I haven't noticed any slow down).
> 
> You can think of it as, by default `torch.compile` makes fp16 compute faster and _more_ precise, but turns out the models and various optimization methods (which were trained/tuned without compile), might "prefer" the _less_ precise numerics (in the mathematical sense), and that's when you need `TORCHINDUCTOR_EMULATE_PRECISION_CASTS=1`.
> 
> I'll chat with the team and see if we can make this experience better for users.

Hi @StrongerXi 

After reinstall windows and make a fresh ComfyUI install I was able to make TORCHINDUCTOR_EMULATE_PRECISION_CASTS=1 work and no noise. Thank you so much

However as you explain, if compile is slower and less precise (it's slower than when I turn compile off), I don't see a reason to do compiling at all

Thank for your effort

**Comment by sinand99** [comment]
@woct0rdho I am having the same problem, will you release a bug fix for this or we can never use fp16 accumulation ??

**Comment by woct0rdho** [comment]
@sinand99 It's being investigated by some PyTorch developers and SageAttention developers, and I'd say this kind of compiler bugs are very hard to deal with. We need to wait for some time until they find a proper fix.

**Comment by sinand99** [comment]
@woct0rdho ok thanks for the information.

**Comment by Ph0rk0z** [comment]
I doubt its from sage itself. I had the same issue with xformers/pt/sage and chroma. The cache node when compiled would produce NaN in the image and make the "static".

**Comment by woct0rdho** [comment]
> It very weird that since I upgrade to Pytorch 2.8 I get a lot of "Python int too large to convert to C long" error when I compile, no matter what I do enable or disable Sage Attention or Fast fp16 accumulation. It seem like ComfyUI has not support full for pytorch 2.8

Hi @pivtienduc , the `OverflowError: Python int too large to convert to C long` bug may be fixed in https://github.com/pytorch/pytorch/issues/162430

**Comment by pivtienduc** [comment]
> > It very weird that since I upgrade to Pytorch 2.8 I get a lot of "Python int too large to convert to C long" error when I compile, no matter what I do enable or disable Sage Attention or Fast fp16 accumulation. It seem like ComfyUI has not support full for pytorch 2.8
> 
> Hi [@pivtienduc](https://github.com/pivtienduc) , the `OverflowError: Python int too large to convert to C long` bug may be fixed in [pytorch/pytorch#162430](https://github.com/pytorch/pytorch/issues/162430)

Thank, I do as the topic said, it remove the Overflow notice and let ComfyUI run but the speed improvement is no where to be seen. So I guess this is it for 3090

**Comment by StrongerXi** [comment]
In case anyone runs into this, the current solutions are either
1. Set `TORCHINDUCTOR_EMULATE_PRECISION_CASTS=1` environment variable
2. Use [this branch](https://github.com/woct0rdho/SageAttention/tree/abi3_stable) per https://github.com/kijai/ComfyUI-WanVideoWrapper/issues/1381#issuecomment-3447919739.

**Comment by Jayluci4** [comment]
@jason-huang03 @jt-zhang - there are two independent bugs compounding here. first, the kernel does not bind to the callers CUDA stream. in non-compiled code this works by luck because PyTorchs default stream is usually the current one, but torch.compile creates subgraph streams and the attention kernel ends up racing with surrounding ops. fix: pass at::cuda::getCurrentCUDAStream() to each kernel launch. second, when allow_fp16_accumulation is on, the running lse value in the online softmax accumulator loses roughly 3 ULPs per tile step in fp16 -- output looks fine for short sequences but degrades past ~512 tokens. fix: force the lse accumulator to fp32 regardless of outer dtype, or bail out of the fused path when fp16 accumulation is detected globally. the parallel_compile branch fixes issue 1 but not issue 2. happy to raise a PR that handles both.
